Created Join Us, Privacy Policy, and History pages
HackIllinois/info-site pull request #26
Opened 2023-08-23 21:07 UTC by tandebnath

2023-08-23 21:43 UTC, nrking0 requested changes
Looks really awesome, just highlighted a few things we can add or look at before merging

2023-08-23 21:43 UTC, nrking0 commented on app/faq/page.module.scss
> +        grid-template-columns: 1fr;
Do we want to reverse order of side-1/side-2 on mobile so the SVG is at the top instead of the middle on mobile?

2023-08-23 21:43 UTC, nrking0 commented on app/history/page.module.scss
> +                .arrow {
Arrow looks like it is doing some wonky stuff on mobile for the last child. Looks great on desktop though!

2023-08-23 21:43 UTC, nrking0 commented on app/history/page.tsx
> +                        ex dolorum dignissimos in deleniti nisi.
We should ask design for words and add before merging

2023-08-23 21:43 UTC, nrking0 commented on components/navbar.tsx
>              <nav className="mobile">
We need to add a join button to mobile

2023-08-23 22:02 UTC, nrking0 commented
Oh I forgot to add this comment, but maybe we could try and scale the staff containers up slightly in the team page

2023-08-23 22:06 UTC, lasyaneti commented on app/join-us/page.tsx
> +                            <input placeholder="Email address" />
Do something similar to this newsletter on the main site:
https://github.com/HackIllinois/site/commit/d119dcfc9f0b24001d65269ffb18fdde37d3eb

Request format: listName "recruitment_interest", emailAddress: text field input

2023-08-23 22:07 UTC, lasyaneti requested changes
Please add the newsletter! API is not a blocker, the endpoint has been ready. Everything else looks great :)

2023-08-23 22:10 UTC, lasyaneti commented on app/history/page.tsx
> +                        ex dolorum dignissimos in deleniti nisi.
We can pull Emily in at the SXD meeting too

2023-08-25 20:13 UTC, anandani4136 commented
**Note:** Accidentally committed instead of raising a PR with my rebased changes, my apologies! Will be more mindful henceforth.

**Change Synopsis:** `Modified the font size for the main page subtext to make it more dynamic and better spaced for larger screens, and tweaked some FAQ information `

2023-08-27 16:19 UTC, nrking0 submitted a review, later dismissed
Looks good!

2023-08-27 16:57 UTC, lasyaneti requested changes
- [ ] Remove hover for past sponsors on mobile screen sizes 
- [ ] Fix scroll view within scroll view for history page, UI for scrolling is really hard to work around 
- [x] Add links to 2017-2021.hackillinois.org

2023-08-27 18:10 UTC, lasyaneti commented on modules/PrivacyPolicyData.ts
> +        title: "HackIllinois’ Privacy Policy",
remove apostrophe

2023-08-27 18:11 UTC, lasyaneti commented
![image](https://github.com/HackIllinois/info-site/assets/44485522/ce4e1c0a-e2a5-4efa-adc7-b2c9c769e678)
mobile landscape UI :(

2023-08-27 18:29 UTC, lasyaneti commented
font consistency, ref: figma <img width="988" alt="image" src="https://github.com/HackIllinois/info-site/assets/44485522/5b29dbb4-f7da-4aca-ab98-5db1914e0981">

2023-08-27 18:30 UTC, lasyaneti commented
font consistency, ref: figma 
![image](https://github.com/HackIllinois/info-site/assets/44485522/b9e88e60-3611-4b13-938f-4936fc71d3b8)
![image](https://github.com/HackIllinois/info-site/assets/44485522/29be176d-4fb7-495e-bcd9-22b9e258a644)

2023-08-27 18:34 UTC, lasyaneti commented
Hardcode the :( so that is in a new line OR honestly just get rid of both the :) and :( <img width="299" alt="image" src="https://github.com/HackIllinois/info-site/assets/44485522/927dc1e1-5078-4fc3-9995-34c9e5b888d2">

2023-08-27 18:41 UTC, lasyaneti commented
Change FAQ page line 18 to:
"Contact us at [contact@hackillinois.org](mailto:contact@hackillinois.org) for involvement or questions regarding HackIllinois. In addition, check out our social medias for the latest information on our events!”

2023-08-27 19:18 UTC, lasyaneti commented
remove extra spacing between divs 
![image](https://github.com/HackIllinois/info-site/assets/44485522/d62aeba8-eb93-4718-871a-3369c6b754e4)

2023-08-28 02:36 UTC, lasyaneti approved these changes
yay

2023-08-28 02:37 UTC, merged