Improved Team Year Selector
HackIllinois/info-site pull request #46
Opened 2024-10-20 14:17 UTC by miguelaenlle

https://github.com/user-attachments/assets/635217be-baf8-4e08-a1cd-d7679c06b18f

- Changed Select component font to Montserrat
- Increased Select component side padding 
- Added dropdown option list animation
- Changed dropdown option list border color to gray

2024-10-25 21:04 UTC, J164 requested changes
This is an amazing start! Would it be possible to add a close button (probably an 'x') to a top corner of the menu on mobile to make the user experience more clear? Great work so far!

2024-10-25 21:04 UTC, J164 commented on components/Select/Select.module.scss
> +    box-shadow: rgba(99, 99, 99, 0.2) 0px -2px 8px 0px;
on mobile its a bit difficult to see the differentiation between the menu and content. Maybe the box shadow could be a bit darker/more obvious?

2024-10-25 21:04 UTC, J164 commented on components/Select/Select.module.scss
> +
Could you increase the border radius on the top of the menu in mobile view? Right now the top of the menu is very flat and it might be more clear with something like 2rem.

2024-10-27 17:51 UTC, miguelaenlle commented
<img width="348" alt="image" src="https://github.com/user-attachments/assets/59d1ffb8-0b72-47b8-a2fa-1bed6742e0f2">

In the last commit, I added the following changes:
- Increased border radius and shadows on dropdown div on mobile
- Added X close button

2024-10-27 17:54 UTC, miguelaenlle commented on components/Select/Select.module.scss
> +
I added this change 👍

2024-10-27 17:54 UTC, miguelaenlle commented on components/Select/Select.module.scss
> +    box-shadow: rgba(99, 99, 99, 0.2) 0px -2px 8px 0px;
I added this change 👍

2024-10-29 02:19 UTC, J164 requested changes
This is awesome! One more thing: on desktop there seems to be a slight misalignment of the years
![image](https://github.com/user-attachments/assets/5d4024f1-bef6-4d57-bdd8-685230e8b4fa)

2024-10-29 03:06 UTC, miguelaenlle commented
![image](https://github.com/user-attachments/assets/6123a42c-616d-4702-86f5-d30995e23515)

- Fixed alignment of buttons in selector
- Slight adjustments to styling of buttons in the selector
- Fixed issue causing the dropdown to stay open when the user clicks the dropdown button multiple times

2024-10-29 15:36 UTC, J164 approved these changes

2024-10-29 15:36 UTC, merged